name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # or your branch of choice

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.7.3'  # Specify your project's Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: npm run build
        env:
          CI: false  # Prevent treating warnings as errors

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build